steps:

  - id: "Rodando docker-compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: ['-f','/app/docker-compose.yaml','up','-d']

  - id: "Docker PS"
    name: 'gcr.io/cloud-builders/docker'
    args: ['ps']

  - id: "Rodando composer"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec','-t','app','composer','install']

  - id: "Copiando .env"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec','-t','app','cp','.env.example','.env']

  - id: "Rodando key:generate"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec','-t','app','php','/app/artisan','key:generate']

  - id: "Rodando migrations"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec','-t','app','php','/app/artisan','migrate']

  - id: "Rodando Phpunit"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec','-t','app','php','/app/vendor/bin/phpunit','-c','/app/phpunit.xml']
