version: '3.4'
services:
  users-api-php:
    container_name: users-api-php
    build:
      context: .
      dockerfile: users.Dockerfile
    depends_on:
      - users-db-mysql
    ports:
      - "8000:80"
    environment:
      - NOOP=
      - DB_URL_MYSQL=users-db-mysql
    volumes:
      - ./:/app

  users-db-mysql:
    container_name: users-db-mysql
    build:
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=root
